config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  
  get  '/users/:user_id/chats/index',           to: 'chat#index',          as: 'chats'
  get  '/users/:user_id/chats/:chat_id',        to: 'chat#show',           as: 'show_chat'
  get  '/users/:user_id/chat/create',          to: 'chat#create',         as: 'create_chat'
  post '/users/:user_id/chat/create_message',  to: 'chat#create_message', as: 'create_message'
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User
 
  validates :sender_id, uniqueness: { scope: :recipient_id }
 
  scope :between, -> (sender_id, recipient_id) do
     where(sender_id: sender_id, recipient_id: recipient_id).or(
       where(sender_id: recipient_id, recipient_id: sender_id)
     )
  end
 
  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end
 
  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  
  validates :body, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :messages, dependent: :destroy
  has_many :conversations, foreign_key: :sender_id
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    session[:conversations] ||= []
    @users = User.all.where.not(id: current_user).without_role :admin
    @conversations = Conversation.includes(:recipient, :messages)             
  end

  def show
    @conversation = Conversation.find(params[:chat_id])
    @messages = @conversation.messages
  end

  def create
    @users = User.all.where.not(id: current_user).without_role :admin
  end
  
  def create_message  
    recipient_id = params[:message][:id]
    @conversation = Conversation.get(current_user.id, recipient_id.to_i)
    add_to_conversations unless conversated?
    @message = @conversation.messages.create!(message_params)    
    redirect_to action: "show",  :chat_id => @conversation.id
  end 
    
  private
  
  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end
 
  def conversated?
    session[:conversations].include?(@conversation.id)
  end
  
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chat/create.html.erb
<%= form_for :message, :url => { :action => "create_message" }, :html => {:class => "form-horizontal"} do |f| %>
	<div class="form-group"><%= f.hidden_field :user_id, value: current_user.id, class: "form-control" %></div>
	<div class="form-group">
		<%= f.label 'To - ' %>
		<%= f.collection_select :id, @users, :id, :email, class: "form-control"%> </div>
 	<div class="form-group"> <%= f.label :body %>
  <%= f.text_area :body, class: "form-control" %></div>
  <%= f.submit 'send', class: "btn btn-default"%>
<% end %>

app/views/chat/index.html.erb
<%= link_to 'create new chat', create_chat_path(current_user), :class => 'btn btn-default' %>

<div class="row">
		<ul id="conversations-list">
			<% @conversations.each do |conversation| %>			
			  <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
		 			<li>
		 			  <div data-conversation-id="<%= conversation.id %>">
		 			      <%= link_to conversation.opposed_user(current_user).email, show_chat_path(current_user, conversation.id) %>
		 			  </div>
		 			</li>
			  <% end %>
			<% end %>
		</ul>
</div>

app/views/chat/show.html.erb
<%= link_to 'Back', chats_path(current_user), :class => 'btn btn-default' %>
<div class="row">
 You are chatting with <%= @conversation.opposed_user(current_user).email %>
</div>
<div class="panel">
<% @messages.each do |message| %>
<div class="row">
	<div class="<%= current_user.id == message.user_id ? 'message-sent' : 'message-received' %>"> <%= message.body%> 
	</div>
</div>
<% end %>
<%= form_for :message, :url => { :action => "create_message" } ,  :html => {:class => "form-inline"} do |f| %>
	<%= f.hidden_field :user_id, value: current_user.id , class: "form-control"%>
	<%= f.hidden_field :id, value: @conversation.opposed_user(current_user).id, class: "form-control" %> 
  <%= f.text_area :body, class: "form-control" %>
  <%= f.submit 'send', class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Edit account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>  
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
					<li><%= link_to 'Chat', chats_path(current_user) %></li>
        <% end %>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Utchat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
			 <div class="container">
			 		<%= yield %>	
			 </div>      
    </main>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>